version: 2version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8.1
    steps:
      - checkout
      - run: echo "master"
  test:
    docker:
      - image: circleci/golang:1.8.1
    steps:
      - checkout
      - run: echo "try161Test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
